module.exports.returnArchiveUrls = function() {

    const blogUrls = [
        "https://bitcointicker.co/news/",
        "https://cointelegraph.com/",
        "https://www.cryptoglobe.com/latest/",
        "https://cointelegraph.com/tags/altcoin",
        "https://www.ccn.com/tag/altcoin-news/",
        "https://www.livebitcoinnews.com/news/altcoin-news/",
        "https://cryptoslate.com/altcoins/",
        "https://www.coininsider.com/category/news/altcoin-news/",
        "https://www.altcoinbuzz.io/category/crypto-news/",
        "https://u.today/",
        "https://www.ccn.com/",
        "https://www.fxstreet.com/cryptocurrencies",
        "https://www.bissresearch.com/",
        "https://www.coindesk.com/",
        "https://www.newsbtc.com/",
        "https://thebitcoinnews.com/",
        "https://cryptonewshub.org/",
        "https://www.newsnow.co.uk/h/Business+&+Finance/Cryptocurrencies",
        "https://cryptocurrencynews.com/",
        "https://www.livebitcoinnews.com/",
        "https://cryptovest.com/news/",
        "https://cointelegraph.com/",
        "https://bitcoinist.com/category/cryptocurrency-news/",
        "https://www.financemagnates.com/cryptocurrency/",
        "https://www.ccn.com/fintech/",
        "https://bitcoinmagazine.com/",
        "https://www.coindesk.com/category/tech",
        "https://cryptonewsreview.com/",
        "https://www.cryptoglobe.com/",
        "https://www.newsbtc.com/",
        "https://www.coinspeaker.com/",
        "https://www.trustnodes.com/",
        "https://cryptocoin.news/",
        "https://www.cryptonewsz.com/",
        "https://dailyhodl.com/",
        "https://coingape.com/news/",
        "https://cryptoslate.com/",
        "https://cryptobriefing.com/",
        "https://ethereumworldnews.com/",
        "https://www.cointelligence.com/",
        "https://blokt.com/news",
        "https://coinnounce.com/",
        "https://cryptopotato.com/",
        "https://blog.chain.link/",
        "https://bitcoinist.com/category/altcoin-news/",
        "https://cryptonews.com/news/altcoin-news/",
        "https://cointelegraph.com/tags/ethereum-classic",
        "https://www.coindesk.com/price/ethereum-classic"

    ];

    //    DONT USE "https://beincrypto.com/altcoin-news/",

    return blogUrls;
  };